import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Box, ChakraProvider } from "@chakra-ui/react";
import theme from "./theme";
import SiteFooter from "./components/SiteFooter";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pcari Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider theme={theme}>
          <Box bg="linear-gradient(to left, black, #2e2e2e)">
            <main>{children}</main>
            <SiteFooter />
          </Box>
        </ChakraProvider>
      </body>
    </html>
  );
}
